execute if score mode qr_uid matches 1 run function QR/generator/generator_7
execute if score mode qr_uid matches 2 run function QR/generator/generator_10
execute if score mode qr_uid matches 3 run function QR/generator/generator_15
execute if score mode qr_uid matches 4 run function QR/generator/generator_20
execute if score mode qr_uid matches 5 run function QR/generator/generator_26
execute if score mode qr_uid matches 6 run function QR/generator/generator_18
execute if score mode qr_uid matches 7 run function QR/generator/generator_20
execute if score mode qr_uid matches 8 run function QR/generator/generator_24
execute if score mode qr_uid matches 9 run function QR/generator/generator_30
execute if score mode qr_uid matches 10 run function QR/generator/generator_18
execute if score mode qr_uid matches 11 run function QR/generator/generator_20
execute if score mode qr_uid matches 12 run function QR/generator/generator_24
execute if score mode qr_uid matches 13 run function QR/generator/generator_26
execute if score mode qr_uid matches 14 run function QR/generator/generator_30
execute if score mode qr_uid matches 15 run function QR/generator/generator_22
execute if score mode qr_uid matches 16 run function QR/generator/generator_24
execute if score mode qr_uid matches 17 run function QR/generator/generator_28
execute if score mode qr_uid matches 18 run function QR/generator/generator_30
execute if score mode qr_uid matches 19..22 run function QR/generator/generator_28
execute if score mode qr_uid matches 23 run function QR/generator/generator_30
execute if score mode qr_uid matches 24 run function QR/generator/generator_30
execute if score mode qr_uid matches 25 run function QR/generator/generator_26
execute if score mode qr_uid matches 26 run function QR/generator/generator_28
execute if score mode qr_uid matches 27..40 run function QR/generator/generator_30