execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=1}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 0
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=2}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 210
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=3}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 171
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=4}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 247
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=5}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 242
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=6}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 93
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=7}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 230
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=8}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 14
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=9}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 109
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=10}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 221
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=11}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 53
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=12}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 200
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=13}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 74
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=14}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 8
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=15}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 172
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=16}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 98
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=17}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 80
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=18}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 219
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=19}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 134
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=20}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 160
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=21}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 105
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=22}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 165
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=23}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 231
