execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=1}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 0
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=2}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 41
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=3}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 173
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=4}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 145
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=5}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 152
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=6}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 216
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=7}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 31
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=8}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 179
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=9}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 182
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=10}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 50
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=11}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 48
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=12}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 110
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=13}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 86
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=14}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 239
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=15}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 96
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=16}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 222
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=17}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 125
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=18}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 42
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=19}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 173
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=20}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 226
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=21}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 193
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=22}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 224
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=23}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 130
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=24}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 156
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=25}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 37
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=26}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 251
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=27}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 216
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=28}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 238
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=29}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 40
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=30}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 192
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=31}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 180