execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=1}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 0
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=2}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 229
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=3}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 121
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=4}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 135
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=5}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 48
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=6}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 211
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=7}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 117
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=8}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 251
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=9}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 126
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=10}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 159
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=11}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 180
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=12}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 169
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=13}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 152
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=14}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 192
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=15}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 226
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=16}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 228
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=17}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 218
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=18}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 111
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=19}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 0
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=20}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 117
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=21}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 232
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=22}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 87
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=23}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 96
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=24}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 227
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=25}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 21
