execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=1}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 0
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=2}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 168
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=3}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 223
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=4}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 200
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=5}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 104
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=6}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 224
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=7}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 234
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=8}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 108
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=9}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 180
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=10}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 110
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=11}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 190
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=12}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 195
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=13}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 147
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=14}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 205
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=15}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 27
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=16}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 232
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=17}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 201
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=18}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 21
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=19}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 43
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=20}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 245
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=21}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 87
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=22}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 42
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=23}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 195
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=24}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 212
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=25}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 119
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=26}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 242
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=27}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 37
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=28}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 9
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=29}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 123
