execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=1}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 0
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=2}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 215
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=3}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 234
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=4}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 158
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=5}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 94
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=6}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 184
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=7}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 97
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=8}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 118
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=9}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 170
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=10}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 79
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=11}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 187
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=12}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 152
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=13}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 148
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=14}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 252
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=15}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 179
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=16}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 5
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=17}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 98
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=18}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 96
execute as @e[name=qr_decode_place] at @s[scores={qr_encode_l=19}] run scoreboard players set @e[c=1,r=2,name=qr_decode] GF_2 153
